### PR TITLE
feat(build): Introduce esbuild

### PR DESCRIPTION
**Pull request by mdovhopo**
I recently tried [esbuild](https://esbuild.github.io/getting-started/#bundling-for-the-browser) to build our cloud function, and found out that it is EXTREMLY fast, you can see on the screenshot below, build of all actions takes just 5 sec... Are we open to allow such change? PR is a draft for now, as we will need to make sure that all scripts work, because esbuild is written in go, instead if usual JS.

Let me know if you are fine with this change, i'll make pipeline green :)

Screenshot 2022-11-16 at 22 43 46

### CODE REVIEW

**Comment by mdovhopo** [comment]
still having some problems with 1 test case... might need some help with it..

**Comment by mdovhopo** [comment]
all done :) platform-specific test was deleted (agreed with @sasjo)

**Review by glebbash — APPROVED** [review]

**Review by sasjo — APPROVED** [review]
Love it ❤️

**Comment by mdovhopo** [comment]
tested this one one of our repo - https://github.com/extenda/hiiretail-txr-search-api/actions/runs/3539802834.

**Review by artemka-debug — APPROVED** [review]

**Pull request merged**
