### PR TITLE
feat: Add Kubernetes action

### PR DESCRIPTION
**Pull request by narmontas**
The `kubernetes` action is similar to `cloud-run`. The service definition can be provided in kubernetes.yaml file in the target repository. The action creates kustomization using kustomize tool and then applies the kubernetes manifest with kubectl.

### CODE REVIEW

**Comment by narmontas** [comment]
I cannot fix the problem with checking /dist/index.js files. It reports that it differs
```
 cloud-run/dist/index.js  | 4 ++--
 iam/dist/index.js        | 4 ++--
 kubernetes/dist/index.js | 4 ++--
 test-pod/dist/index.js   | 4 ++--
 4 files changed, 8 insertions(+), 8 deletions(-)
```

When I run `npm build run` locally, it does not create any changes. Can it be due to incompatability between line-feeds?

**Comment by narmontas** [comment]
> I cannot fix the problem with checking /dist/index.js files. It reports that it differs
> 
> ```
>  cloud-run/dist/index.js  | 4 ++--
>  iam/dist/index.js        | 4 ++--
>  kubernetes/dist/index.js | 4 ++--
>  test-pod/dist/index.js   | 4 ++--
>  4 files changed, 8 insertions(+), 8 deletions(-)
> ```
> 
> When I run `npm build run` locally, it does not create any changes. Can it be due to incompatability between line-feeds?

Solved by running pre-commit. This PR is ready for review.

**Review by sasjo — APPROVED** [review]
Looks good, but I have a few questions:

* When using this action and Kubernetes.yaml, do you also need to specify any manifests (pods, deployments etc) or is everything generated from this action?
* The YAMLs we generate contain some hardcoded ER or Hii Retail specific data. This makes the action hard to use outside of ER. Not a big deal, but something we could avoid with optional inputs and default values.
* Will this action work with OPA side car injection automatically? (I think so because Istio does it)

**Comment by narmontas** [comment]
@sasjo I have added code changes to support both `Deployment` and `StatefulSet` based on `kubernetes.yaml` if storage is defined in there.

**Review by sasjo — APPROVED** [review]

**Comment by sasjo** [comment]
Thanks @narmontas, looks like a great contribution!

**Pull request merged**
